apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: guestbook
  name: guestbook-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: guestbook.bbros.xyz
    http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: guestbook-ui
              port:
                number: 80